-- Regression coverage for rendered height, editing events, and window resizing.
vim.opt.runtimepath:append(vim.uv.cwd())
vim.o.lines = 50
vim.o.columns = 120
local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
local path = root .. "/example.lua"
vim.fn.writefile({ "local a = 1", "local b = 2", "return a + b" }, path)
require("local_review").setup({ storage_dir = root .. "/state", comment_box_width = 48 })
vim.cmd.edit(path)
vim.cmd.vsplit()
local source = vim.api.nvim_get_current_win()
local ui = require("local_review.ui")
ui.open_current_line()
vim.wait(20)
local editor = vim.api.nvim_get_current_win()
local bufnr = vim.api.nvim_get_current_buf()
local function change(lines, event)
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
  vim.api.nvim_exec_autocmds(event or "TextChanged", { buffer = bufnr })
end
local function height()
  return vim.api.nvim_win_get_height(editor)
end
local function assert_fits()
  local rendered = vim.api.nvim_win_text_height(editor, {}).all
  assert(height() == math.max(3, rendered), "editor must fit rendered text, not just logical lines")
  local view = vim.api.nvim_win_call(editor, vim.fn.winsaveview)
  assert(view.topline == 1 and view.skipcol == 0, "a fitting comment must be visible from its beginning")
end

assert(height() == 3, "restore the original three-row minimum")
change({ " " .. string.rep("word ", 40) }, "TextChangedI")
assert_fits()
assert(height() > 3, "wrapped text must grow the editor")
change({ " short" }, "TextChangedI")
assert(height() == 3, "deleting text must shrink the editor")
change({ " a", " b", " c", " d", " e", " f" })
assert(height() == 6, "newlines must grow the editor")
vim.api.nvim_win_set_cursor(editor, { 6, 0 })
vim.api.nvim_win_call(editor, function()
  vim.fn.winrestview({ topline = 4 })
end)
vim.api.nvim_exec_autocmds("CursorMoved", { buffer = bufnr })
assert_fits()
change({ " short", "", "", "", "", "" })
vim.api.nvim_win_set_cursor(editor, { 6, 0 })
vim.api.nvim_exec_autocmds("CursorMovedI", { buffer = bufnr })
assert(height() == 6, "keep the current blank line visible")
vim.api.nvim_win_set_cursor(editor, { 1, 0 })
vim.api.nvim_exec_autocmds("CursorMoved", { buffer = bufnr })
assert(height() == 3, "shrink trailing blank space when the cursor leaves it")

change({ " " .. string.rep("界", 80) }, "TextChangedP")
assert_fits()
change({ " code\t" .. string.rep("word ", 28) })
assert_fits()
local wide_height = height()
vim.api.nvim_win_set_width(source, 25)
vim.api.nvim_exec_autocmds("WinResized", {})
assert(vim.api.nvim_win_get_width(editor) <= 23, "editor must follow source-window width")
assert_fits()
assert(height() > wide_height, "narrowing must add wrapped rows")
vim.api.nvim_win_set_width(source, 65)
vim.api.nvim_exec_autocmds("VimResized", {})
assert(vim.api.nvim_win_get_width(editor) == 48, "widening restores configured width")
assert_fits()

-- A short source window must cap the float, without losing stored text.
vim.api.nvim_win_call(source, function()
  vim.cmd.split()
end)
vim.api.nvim_set_current_win(editor)
vim.api.nvim_win_set_height(source, 5)
vim.api.nvim_exec_autocmds("WinResized", {})
assert(height() <= 3, "float and borders must fit a short source window")
assert(ui.close_active())
vim.fn.delete(root, "rf")
print("PASS: editor grows, shrinks, wraps Unicode/tabs, follows window size, and respects height limits")
